# Generated by Django 4.0.5 on 2022-07-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='tag',
        ),
        migrations.DeleteModel(
            name='TagModel',
        ),
    ]
